import { faker } from '@faker-js/faker';
import { Movie, User, Review } from '../types';

// Real movie data (Bollywood & Hollywood) with reliable poster URLs
const realMovies: Movie[] = [
  // --- NEW 2025 MOVIES ---
  {
    id: 'tt14511142',
    title: 'Captain America: Brave New World',
    genre: ['Action', 'Sci-Fi', 'Adventure'],
    releaseYear: 2025,
    director: 'Julius Onah',
    cast: ['Anthony Mackie', 'Harrison Ford', 'Tim Blake Nelson', 'Shira Haas'],
    synopsis: 'Sam Wilson, now Captain America, grapples with his new role and faces a global threat led by The Leader.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/2/25/Captain_America_Brave_New_World_teaser_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=example',
    averageRating: 4.8,
    totalReviews: 0,
    duration: 150,
    featured: true,
    trending: true,
  },
  {
    id: 'tt9680444',
    title: 'Mission: Impossible - The Final Reckoning',
    genre: ['Action', 'Adventure', 'Thriller'],
    releaseYear: 2025,
    director: 'Christopher McQuarrie',
    cast: ['Tom Cruise', 'Hayley Atwell', 'Ving Rhames', 'Simon Pegg'],
    synopsis: 'Ethan Hunt and his IMF team embark on their most dangerous mission yet, a final confrontation with "The Entity".',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/3/34/Mission_Impossible_-_The_Final_Reckoning.jpg/220px-Mission_Impossible_-_The_Final_Reckoning.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=example',
    averageRating: 4.9,
    totalReviews: 0,
    duration: 160,
    featured: true,
  },
  {
    id: 'tt26443804',
    title: 'War 2',
    genre: ['Action', 'Thriller'],
    releaseYear: 2025,
    director: 'Ayan Mukerji',
    cast: ['Hrithik Roshan', 'N. T. Rama Rao Jr.', 'Kiara Advani'],
    synopsis: 'A sequel to the 2019 blockbuster, this film expands the YRF Spy Universe with a new high-stakes mission.',
    posterUrl: 'https://images.unsplash.com/photo-1509347528160-9a9e33742cdb?w=500&h=750&fit=crop',
    trailerUrl: 'https://www.youtube.com/watch?v=example',
    averageRating: 4.7,
    totalReviews: 0,
    duration: 155,
    trending: true,
  },

  // --- EXISTING MOVIES ---
  {
    id: 'tt15341822',
    title: 'Kalki 2898-AD',
    genre: ['Sci-Fi', 'Action', 'Adventure'],
    releaseYear: 2024,
    director: 'Nag Ashwin',
    cast: ['Prabhas', 'Amitabh Bachchan', 'Kamal Haasan', 'Deepika Padukone', 'Disha Patani'],
    synopsis: 'A modern-day avatar of the Hindu god Vishnu, who is believed to have descended to Earth to protect the world from evil forces.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/9/95/Kalki_2898_AD_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=kQDd1FFfvXg',
    averageRating: 4.8,
    totalReviews: 1500,
    duration: 180,
    featured: true,
    trending: true,
  },
  {
    id: 'tt21802348',
    title: 'Fighter',
    genre: ['Action', 'Thriller'],
    releaseYear: 2024,
    director: 'Siddharth Anand',
    cast: ['Hrithik Roshan', 'Deepika Padukone', 'Anil Kapoor'],
    synopsis: 'Top IAF aviators come together in the face of imminent danger, to form Air Dragons. Fighter unfolds their camaraderie, brotherhood and battles, internal and external.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c9/Fighter_2024_film_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=970eQbe8S3s',
    averageRating: 4.2,
    totalReviews: 980,
    duration: 166,
    trending: true,
  },
  {
    id: 'tt27405196',
    title: 'Singham Again',
    genre: ['Action', 'Drama'],
    releaseYear: 2024,
    director: 'Rohit Shetty',
    cast: ['Ajay Devgn', 'Akshay Kumar', 'Ranveer Singh', 'Deepika Padukone', 'Tiger Shroff', 'Kareena Kapoor Khan'],
    synopsis: 'The third installment of the Singham franchise, where the fearless cop Bajirao Singham takes on a new and formidable enemy.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/4/45/Singham_Again_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=example',
    averageRating: 4.5,
    totalReviews: 1200,
    duration: 150,
    featured: true,
  },
  {
    id: 'tt12844910',
    title: 'Stree 2',
    genre: ['Horror', 'Comedy'],
    releaseYear: 2024,
    director: 'Amar Kaushik',
    cast: ['Shraddha Kapoor', 'Rajkummar Rao', 'Pankaj Tripathi', 'Aparshakti Khurana'],
    synopsis: 'The sequel to the successful horror-comedy, where the residents of Chanderi face a new supernatural threat.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e7/Stree_2_film_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=example',
    averageRating: 4.3,
    totalReviews: 850,
    duration: 135,
    trending: true,
  },
  {
    id: 'tt15677242',
    title: 'Bade Miyan Chote Miyan',
    genre: ['Action', 'Comedy', 'Sci-Fi'],
    releaseYear: 2024,
    director: 'Ali Abbas Zafar',
    cast: ['Akshay Kumar', 'Tiger Shroff', 'Prithviraj Sukumaran', 'Sonakshi Sinha'],
    synopsis: 'Two elite soldiers with contrasting personalities and methods are forced to team up to recover a stolen weapon from a brilliant and ruthless scientist.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b2/Bade_Miyan_Chote_Miyan_2024_film_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=f15h3_yDk3A',
    averageRating: 3.8,
    totalReviews: 750,
    duration: 164,
  },
  {
    id: 'tt28684425',
    title: 'Mr. & Mrs. Mahi',
    genre: ['Drama', 'Romance', 'Sport'],
    releaseYear: 2024,
    director: 'Sharan Sharma',
    cast: ['Janhvi Kapoor', 'Rajkummar Rao'],
    synopsis: 'An imperfectly perfect partnership of a married couple who share a love for cricket.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1a/Mr._%26_Mrs._Mahi_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=example',
    averageRating: 4.1,
    totalReviews: 600,
    duration: 140,
  },
  {
    id: 'tt6718170',
    title: 'The Super Mario Bros. Movie',
    genre: ['Animation', 'Adventure', 'Comedy'],
    releaseYear: 2023,
    director: 'Aaron Horvath, Michael Jelenic',
    cast: ['Chris Pratt', 'Anya Taylor-Joy', 'Charlie Day', 'Jack Black', 'Seth Rogen'],
    synopsis: 'A plumber named Mario travels through an underground labyrinth with his brother, Luigi, trying to save a captured princess.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/4/44/The_Super_Mario_Bros._Movie_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=TnGl01FkMMo',
    averageRating: 4.6,
    totalReviews: 2500,
    duration: 92,
    featured: true,
  },
  {
    id: 'tt10676048',
    title: 'Deadpool & Wolverine',
    genre: ['Action', 'Comedy', 'Sci-Fi'],
    releaseYear: 2024,
    director: 'Shawn Levy',
    cast: ['Ryan Reynolds', 'Hugh Jackman', 'Emma Corrin'],
    synopsis: 'Wolverine is recovering from his injuries when he crosses paths with the loudmouth, Deadpool. They team up to defeat a common enemy.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4c/Deadpool_%26_Wolverine_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=73_1biK-DAA',
    averageRating: 4.9,
    totalReviews: 3200,
    duration: 127,
    featured: true,
    trending: true,
  },
  {
    id: 'tt12253228',
    title: 'Dune: Part Two',
    genre: ['Sci-Fi', 'Adventure', 'Drama'],
    releaseYear: 2024,
    director: 'Denis Villeneuve',
    cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Austin Butler'],
    synopsis: 'Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/5/52/Dune_Part_Two.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=U2Qp5pL3ovA',
    averageRating: 4.7,
    totalReviews: 2800,
    duration: 166,
    trending: true,
  },
  {
    id: 'tt1630029',
    title: 'Avatar',
    genre: ['Sci-Fi', 'Action', 'Adventure'],
    releaseYear: 2009,
    director: 'James Cameron',
    cast: ['Sam Worthington', 'Zoe Saldaña', 'Sigourney Weaver', 'Stephen Lang'],
    synopsis: 'A paraplegic marine dispatched to the moon Pandora on a unique mission becomes torn between following orders and protecting the world he feels is his home.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d6/Avatar_%282009_film%29_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=5PSNL1qE6VY',
    averageRating: 4.8,
    totalReviews: 4000,
    duration: 162,
    featured: true,
  },
  {
    id: 'tt13238346',
    title: 'Inside Out 2',
    genre: ['Animation', 'Comedy', 'Family'],
    releaseYear: 2024,
    director: 'Kelsey Mann',
    cast: ['Amy Poehler', 'Phyllis Smith', 'Lewis Black', 'Maya Hawke'],
    synopsis: 'Follows Riley, in her teenage years, encountering new emotions.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/4/45/Inside_Out_2_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=LEjhY15eCx0',
    averageRating: 4.5,
    totalReviews: 1800,
    duration: 100,
    trending: true,
  },
  {
    id: 'tt14539740',
    title: 'Godzilla x Kong: The New Empire',
    genre: ['Action', 'Sci-Fi', 'Thriller'],
    releaseYear: 2024,
    director: 'Adam Wingard',
    cast: ['Rebecca Hall', 'Brian Tyree Henry', 'Dan Stevens'],
    synopsis: 'Two ancient titans, Godzilla and Kong, clash in an epic battle as humans unravel their intertwined origins and connection to Skull Island\'s mysteries.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b8/Godzilla_x_Kong_The_New_Empire_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=qqrpMRDuPfc',
    averageRating: 4.0,
    totalReviews: 1600,
    duration: 115,
  },
  {
    id: 'tt2253724',
    title: 'Joker: Folie à Deux',
    genre: ['Crime', 'Drama', 'Musical'],
    releaseYear: 2024,
    director: 'Todd Phillips',
    cast: ['Joaquin Phoenix', 'Lady Gaga', 'Zazie Beetz'],
    synopsis: 'The sequel to Joker (2019), this musical thriller continues the story of Arthur Fleck and introduces Harley Quinn.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/f/f3/Joker_Folie_%C3%A0_Deux_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=xy8aJw1vYHo',
    averageRating: 4.6,
    totalReviews: 2200,
    duration: 150,
    trending: true,
  },
  {
    id: 'tt12737888',
    title: 'Furiosa: A Mad Max Saga',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    releaseYear: 2024,
    director: 'George Miller',
    cast: ['Anya Taylor-Joy', 'Chris Hemsworth', 'Tom Burke'],
    synopsis: 'The origin story of renegade warrior Furiosa before she teamed up with Mad Max in "Fury Road".',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d9/Furiosa_A_Mad_Max_Saga_poster.jpeg',
    trailerUrl: 'https://www.youtube.com/watch?v=XJMuhwVlca4',
    averageRating: 4.4,
    totalReviews: 1750,
    duration: 148,
  },
  {
    id: 'tt7466810',
    title: 'The Fall Guy',
    genre: ['Action', 'Comedy', 'Drama'],
    releaseYear: 2024,
    director: 'David Leitch',
    cast: ['Ryan Gosling', 'Emily Blunt', 'Aaron Taylor-Johnson'],
    synopsis: 'A down-and-out stuntman must find the missing star of his ex-girlfriend\'s blockbuster film.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b5/The_Fall_Guy_poster.jpg',
    trailerUrl: 'https://www.youtube.com/watch?v=j7jPnlb7C88',
    averageRating: 4.2,
    totalReviews: 1100,
    duration: 126,
  },
];


// Generate mock movies
export const generateMockMovies = (count: number = 50): Movie[] => {
  // Shuffle the realMovies array to provide variety
  const shuffled = [...realMovies].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};

// Generate mock user
export const generateMockUser = (): User => ({
  id: faker.string.uuid(),
  username: faker.internet.username(),
  email: faker.internet.email(),
  profilePicture: faker.image.avatar(),
  joinDate: faker.date.past({ years: 2 }).toISOString(),
  totalReviews: faker.number.int({ min: 0, max: 50 }),
});

// Generate mock reviews
export const generateMockReviews = (movieId: string, count: number = 10): Review[] => {
  const reviews: Review[] = [];
  
  for (let i = 0; i < count; i++) {
    const review: Review = {
      id: faker.string.uuid(),
      userId: faker.string.uuid(),
      movieId,
      rating: faker.number.int({ min: 1, max: 5 }),
      reviewText: faker.lorem.paragraphs(faker.number.int({ min: 1, max: 3 })),
      timestamp: faker.date.past({ years: 1 }).toISOString(),
      user: {
        username: faker.internet.username(),
        profilePicture: faker.image.avatar(),
      },
    };
    reviews.push(review);
  }
  
  return reviews;
};
